((nil . ((indent-tabs-mode . nil)
         (fill-column . 70)))
 (verilog-mode . ((verilog-indent-level . 2)
                  (verilog-indent-level-module . 2)
                  (verilog-indent-level-declaration . 2)
                  (verilog-indent-level-behavioral . 2)
                  (verilog-indent-level-directive . 2)
                  (verilog-case-indent . 2)
                  (verilog-auto-lineup . nil))))
